In [17]:
import numpy as np
rand_num = np.random.randn(25)
print(rand_num)

[-0.08986846  0.6537338   1.01765307 -0.18855778 -0.48237575 -0.44581606
  0.2044515   0.39409614 -0.71470457 -1.12500004 -1.65179792 -0.52820621
 -1.23265027  0.61345932  1.91194215 -0.56030608  1.14949511  1.08174808
  0.21295484  0.9664572   0.667451    0.00780345  0.60395335 -0.46452836
  0.82598174]


In [18]:
import numpy as np
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [5]:
arr=np.arange(1,101).reshape(10,10)
print(arr)


[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [11]:
print(arr[[1,5,6]])

[[11 12 13 14 15 16 17 18 19 20]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]]


In [21]:
print(arr[2:])

[[ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [37]:
print(arr[:,3:8])

[[ 4  5  6  7  8]
 [14 15 16 17 18]
 [24 25 26 27 28]
 [34 35 36 37 38]
 [44 45 46 47 48]
 [54 55 56 57 58]
 [64 65 66 67 68]
 [74 75 76 77 78]
 [84 85 86 87 88]
 [94 95 96 97 98]]


In [20]:
print(arr[2:5,1:8])

[[22 23 24 25 26 27 28]
 [32 33 34 35 36 37 38]
 [42 43 44 45 46 47 48]]


In [22]:
np.random.rand(1000)

array([0.3200176 , 0.20511619, 0.01163192, 0.36477758, 0.22086499,
       0.83771972, 0.52261477, 0.24419   , 0.84378641, 0.84359256,
       0.14065612, 0.63973281, 0.37214892, 0.42343288, 0.06239379,
       0.5365389 , 0.77455247, 0.34677207, 0.32022827, 0.71675567,
       0.6849411 , 0.925848  , 0.89754911, 0.91106833, 0.82741781,
       0.84491859, 0.90475462, 0.29356654, 0.21958372, 0.86105772,
       0.91913583, 0.4795923 , 0.76105515, 0.20863844, 0.43129293,
       0.30794615, 0.3878368 , 0.78063555, 0.66922581, 0.21993492,
       0.28375759, 0.28833401, 0.27977667, 0.01519757, 0.48174813,
       0.49871431, 0.73891695, 0.09033955, 0.97541024, 0.05597399,
       0.21115083, 0.18876493, 0.00830047, 0.24303107, 0.61191522,
       0.07568947, 0.96329602, 0.96038764, 0.15963959, 0.14230261,
       0.0778476 , 0.53677379, 0.34888033, 0.13674152, 0.1437527 ,
       0.4865979 , 0.45521696, 0.64627946, 0.28797826, 0.33863968,
       0.64033267, 0.986094  , 0.76347529, 0.71310211, 0.46100

In [8]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [9]:
np.median(a)

4.5

In [10]:
np.std(a)

1.8027756377319946

In [11]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a


array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [14]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))